<!DOCTYPE HTML><!-- skel-baseline v3.0.0 | (c) n33 | skel.io | MIT licensed --><html><head><title>Feedback Corner - Welcome to my new Personal Website</title><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><link rel="stylesheet" href="assets/css/main.css" /></head><body id="top"><!-- Header --><header id="header"><h1><a href="index.php">Donald Leung <span style="font-size: 0.6em;">Feedback Corner</span></a></h1></header><!-- Main --><div id="main" class="container"><div class="row"><div class="12u$"><h2>Welcome to my new Personal Website</h2><p style="font-size: smaller; font-style: italic;">Created by <a href="mailto:dleung@connect.kellettschool.com">Donald Leung</a> at 21-10-2015 02:17 pm | Website: <a href="http://naitsabes.com">http://naitsabes.com</a></p><div style="display: block;"><p>Welcome to my new Personal Website hosted at <a href="http://naitsabes.com">http://naitsabes.com</a>!  Previously, I have been fiddling with <a href="https://pages.github.com">GitHub User Sites</a> for over a year now, so I decided it was time to get a website domain for real.</p>

<p>In case you haven't noticed, there are a few things that are new in this website:</p>

<ol>
<li>An actual <strong>working PHP contact form</strong> - previously, the contact form I had on my GitHub User Site was powered by Javascript which actually wasn't meant for sending emails in the first place</li>
<li>A working <strong>PHP Feedback Corner</strong> where you can easily create posts and comment on them!  The "Forums" I had in my GitHub User Site was extremely inconvenient due to the fact that it operated on pure Javascript - for example, to create a post or comment on a post, you had to send me an email to ask me to add the comment/post onto the "Forums" manually</li>
</ol>

<p>I haven't been able to code a real working Forum yet on this site because I still don't know how to manipulate databases with PHP but once I learn how to do it properly, I will code it as soon as possible!</p></div><p><a href="comment.php?append=1,565,884,335_Welcome to my new Personal Website.snippet.html" class="button">Comment</a></p><h3>Comments</h3><p>Below are the comments left by various people.</p><ul class="alt"><?php $my_snippet = fopen("1,565,884,335_Welcome to my new Personal Website.snippet.html", "r") or die("Unable to open my snippet file!"); echo fread($my_snippet, filesize("1,565,884,335_Welcome to my new Personal Website.snippet.html")); fclose($my_snippet); ?></ul></div></div></div><!-- Footer --><footer id="footer"><div class="copyright">&copy; 2015 Donald Leung. All rights reserved.</div></footer><!-- Scripts --><script src="assets/js/skel.min.js"></script><script src="assets/js/main.js"></script></body></html>